### PR TITLE
Added new iOS Client with prettier interface in its WWW folder.

### PR DESCRIPTION
**Pull request by josefdlange**
We should probably integrate this WWW with the one that's supposed to be "unified", but for now I wanted to get this code onto GitHub.

### CODE REVIEW

**Comment by krwenholz** [comment]
Hey Joey,

Why can't this guy go into the regular www folder?  I'm a little concerned that adding a www folder in human-pong may screw up some gitignore things and set us off on where each piece of the project is.  Any thoughts?

**Comment by josefdlange** [comment]
A good point. Let's chat between 281 and 340 and maybe merge my www
into the www repository?

Sent from my iPhone

On Nov 21, 2011, at 1:01 PM, Kyle
reply@reply.github.com
wrote:

**Comment by josefdlange** [comment]
I'm going to remove the www folder from the PongClient directory to adhere to our source control standards, commit that, then try to merge it.

**Comment by josefdlange** [comment]
Okay, go ahead and pull this in, it shouldn't be a problem anymore.

**Pull request merged**
