### PR TITLE
Fixed up the TestPong demo

### PR DESCRIPTION
**Pull request by krwenholz**
Man this thing is ugly, but it looks more like ours and functionality is only some steps away.  The code is also getting some comments.  Hooray for readable CSS files!

### CODE REVIEW

**Comment by dguilak** [comment]
Might I suggest http://github.com/german/pong ? I got it working on the server ...

**Comment by krwenholz** [comment]
I like the look of that one.  The one I'm requesting here is basically just an interface built in phonegap.  It's nothing fancy and is really just a prototype.  It'll probably get scrapped over the weekend in favor of something like the german/pong game you linked to.

**Comment by dguilak** [comment]
I'm gonna talk with the team this weekend and see if they want to go the JavaScript route -- it would suck to learn a new language, but JS is syntactically really similar to Java, and there's examples and support in excess. Java WebSocket implementations seem to be a little new and perhaps a tad bloated. But the pong game has quite a few good modules that we could use.

**Comment by krwenholz** [comment]
So, I hate to be a nag, but if a manager could merge this sucker. . . . I'm trying to be patient and not abuse my ability to push.

**Pull request merged**
